install: gradle wrapper --gradle-version 4.2
language: java
jdk:
- oraclejdk8
script:
- "./gradlew build --scan -s"
env:
  - SERVER_IP_ADDRESS=43.241.225.147 USER=kenvi

before_install:
- openssl aes-256-cbc -K $encrypted_94f816c05403_key -iv $encrypted_94f816c05403_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "#(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

after_success:
  - scp ./build/libs/*.jar $USER@$SERVER_IP_ADDRESS:/usr/$USER/wechat/beta
